In [24]:
import array
a=array.array('i',[1,2,3,4,5,6])
for i in range (0,6):
    b=array.array('l',[6,9,3,78,5,2,6,])
    for l in range (0,7):
        print(b[l])
    print(a[i])

6
9
3
78
5
2
6
1
6
9
3
78
5
2
6
2
6
9
3
78
5
2
6
3
6
9
3
78
5
2
6
4
6
9
3
78
5
2
6
5
6
9
3
78
5
2
6
6


In [25]:
import array
arr=array.array('i',[1,2,3,4,5,6])
arr.append(50)
print(arr)


arr12=array.array('i',sorted(arr))
print(arr12)

newarr=arr.tolist()
print(newarr)

array('i', [1, 2, 3, 4, 5, 6, 50])
array('i', [1, 2, 3, 4, 5, 6, 50])
[1, 2, 3, 4, 5, 6, 50]


In [26]:
import numpy as np
arr=np.array([[1,4,4],[4,3,8]])
print(arr1.shape)


(2, 3)


In [27]:
import numpy as np
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar2.shape)

(3, 3)


In [5]:
a1=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a1.reshape(6,2))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [37]:
a=np.array([[2,3,4],[5,3,7]])
print(a2.ndim)


1


In [38]:
a1=np.array([2,4,7,5,3,6,9,5,3,9])
print(a3.dtype)

int64


In [39]:
a2=np.array([2,3,4,7,2,6,8,7,9])
print(a4.size)

9


In [40]:
a3=np.array([[2,3,4,5],[6,7,8,9]])
print(a5[1][2])
print(a5)

8
[[2 3 4 5]
 [6 7 8 9]]


In [41]:
a4=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(a6[1][1])
print("-----------")
print(a6)
print("*********")
print(a6[0:1])
print("*********")
print(a6[:,1])
print("*********")

7
-----------
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
*********
[[1 2 3 4 5]]
*********
[ 2  7 12]
*********


In [11]:
b=np.array([1,2,3])

print(b+2)
print(b*2)

[3 4 5]
[2 4 6]


In [12]:
b1=np.array([2,4,6,8])
print(np.sum(b1))
print(np.mean(b1))
print(np.median(b1))
print(np.max(b1))
print(np.min(b1))

20
5.0
5.0
8
2


In [13]:
b2=np.array([7,2,7,9,3,7,4,2,6,9,2,6])
print(np.median(b2))

6.0


In [49]:
a = np.array([1,2,3,4,5,6])
b = a.reshape([2,3])
print(b)
print(a.flatten())

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [16]:
a=np.array([1,2,3,5,7,8,3,5,0,6,3])
print(np.arange(0,11))

[ 0  1  2  3  4  5  6  7  8  9 10]


In [20]:
a=np.array([3,8,3,2,5,8,4,2])
print(np.linspace(0,1,3))
print(np.ones(len(a)))

[0.  0.5 1. ]
[1. 1. 1. 1. 1. 1. 1. 1.]


In [21]:
a = np.array([[2,3,4,5,6],[3,5,7,1,5]])
print(np.sum(a))
print(np.sum(a,axis=1))

41
[20 21]


In [22]:
np.ones(3)

array([1., 1., 1.])

In [23]:
np.zeros(4)

array([0., 0., 0., 0.])

In [53]:
a1=np.array ([[1,2,3], [5,3,6]])
print(a1.shape)
b1=np.array ([[4,8,3,4], [62,8,1,5], [6,2,5,7]])
print(b1.shape)
print(np.dot(a1,b1))

(2, 3)
(3, 4)
[[146  30  20  35]
 [242  76  48  77]]


In [54]:
np.random.random([3,4])

array([[0.61007252, 0.81284218, 0.13758791, 0.14413561],
       [0.49987674, 0.28908436, 0.04077371, 0.36586172],
       [0.95869856, 0.96264279, 0.4286733 , 0.78440845]])

In [60]:
import numpy as np


rng = np.random.default_rng()
rng.integers(6, size=(2, 4))

array([[2, 2, 5, 2],
       [0, 4, 4, 5]])

In [62]:
a1=np. array ([[1,3,4,6], [67,1,4,9]])
b1=np. array ([[4,8,3,4], [62,8,1,5]])
add=np.add (a1,b1)
print (add)
sub=np.subtract(a1,b1)
print (sub)
sclar=3*a1

[[  5  11   7  10]
 [129   9   5  14]]
[[-3 -5  1  2]
 [ 5 -7  3  4]]
